name: flutter_pos_transfer
description: A Flutter POS background upload/download module with Cubit state management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # HTTP Client
  dio: ^5.9.0

  # File Handling
  file_picker: ^10.3.7
  path_provider: ^2.1.5

  # Notifications
  flutter_local_notifications: ^19.5.0

  # Storage & Persistence
  shared_preferences: ^2.5.3

  # Permissions
  permission_handler: ^12.0.1

  connectivity_plus: ^7.0.0


  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true